name: msix
description: A command-line tool that create Msix installer from your flutter windows-build files.
version: 3.16.12
maintainer: Yehuda Kremer (yehudakremer@gmail.com)
homepage: https://github.com/YehudaKremer/msix
issue_tracker: https://github.com/YehudaKremer/msix/issues
topics:
  - windows
  - tool
screenshots:
  - description: "A command-line tool that create Msix installer from your flutter windows-build files."
    path: doc/screenshot.png

platforms:
  windows:

environment:
  sdk: ">=3.8.0"

dependencies:
  args: ^2.7.0
  yaml: ^3.1.3
  path: ^1.9.1
  package_config: ^2.2.0
  get_it: ^9.0.3
  image: ^4.5.4
  pub_semver: ^2.2.0
  console: ^4.1.0
  cli_util: ^0.4.2

dev_dependencies:
  test: ^1.26.3
  flutter_lints: ^6.0.0
